### ISSUE TITLE
Question about human proxy model

### ISSUE THREAD

**Issue by CILabTaegwan** [LxzGordon/pecan_human_AI_coordination#1]
Hi, I would like to ask about the experimental procedure in your paper.

How could you get a human proxy model that has been used in your paper and previous baseline (mep, fcp, pbt,...)? Did you train a behavior-cloning agent at PantheonRL?

I would appreciate it if you could answer my question.

**Comment by LxzGordon** [comment]
Human proxy models are behavior-cloning agents from human data. We reuse the human proxy model from the BCP paper, as did previous baselines. They are provided in https://github.com/LxzGordon/PECAN/tree/master/human_aware_rl/human_aware_rl/data/bc_runs
